version: "3.7"

services:

  phanghon:
    build:
      context: .
      dockerfile: Dockerfile.PhanGhon
    env_file: .env
    ports:
      - 8000:8000
    command: ["gunicorn", "siteconfig.wsgi"]
    image: phanghon
