version: "3.7"

services:

  phanghon:
    build:
      context: .
      dockerfile: Dockerfile.PhanGhon
    image: phanghon
    env_file: .env
    ports:
      - 8000:8000
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
