FROM ubuntu:20.04

RUN apt update
RUN apt install -y python3.8 pipenv

WORKDIR /home

COPY PhanGhon .
COPY Pipfile .
COPY Pipfile.lock .
COPY .env .

RUN pipenv install --system

EXPOSE 8000

# RUN apt install pipenv3